export default {
  timeline: {},
  timelineTrack: {},
  marker: {},
  card: {},
  button: {},
  dateContainer: {},
  date: {},
  conditionalMarkdown: {},
  imageAtom: {},
  imageCredit: {},
  imageText: {},
  tweetText: {},
  youTubeText: {},
  events: {},
  event: {},
  eventDateColumn: {},
  eventMarkerColumn: {},
  eventCardColumn: {},
};
